export type GenreId = number;
export type GenreEntryType = "Anime" | "Manga";

export interface GenreData<T extends GenreEntryType = GenreEntryType> {
    id: GenreId;
    name: ExactEnglishGenreType;
    russian: ExactRussianGenreType;
    kind: "genre";
    entry_type: T;
}
export type ExactEnglishGenreType = (string & {}) | (typeof exactEnglishGenres)[number];
export type ExactRussianGenreType = (string & {}) | (typeof exactRussianGenres)[number];
export const exactEnglishGenres = [
    "Police",
    "Drama",
    "Game",
    "Psychological",
    "Demons",
    "Josei",
    "Yuri",
    "Shounen",
    "Comedy",
    "Supernatural",
    "Ecchi",
    "Shoujo",
    "Vampire",
    "Yaoi",
    "Music",
    "Samurai",
    "Action",
    "Parody",
    "Slice of Life",
    "Mecha",
    "Romance",
    "Historical",
    "Fantasy",
    "Magic",
    "Harem",
    "Sports",
    "Hentai",
    "School",
    "Sci-Fi",
    "Shoujo Ai",
    "Gender Bender",
    "Doujinshi",
    "Thriller",
    "Super Power",
    "Mystery",
    "Military",
    "Kids",
    "Cars",
    "Martial Arts",
    "Dementia",
    "Seinen",
    "Shounen Ai",
    "Gourmet",
    "Space",
    "Work Life",
    "Horror",
    "Adventure",
    "Erotica",
] as const;
export const exactRussianGenres = [
    "Полиция",
    "Драма",
    "Игры",
    "Психологическое",
    "Демоны",
    "Дзёсей",
    "Юри",
    "Сёнен",
    "Комедия",
    "Сверхъестественное",
    "Этти",
    "Сёдзе",
    "Вампиры",
    "Яой",
    "Музыка",
    "Самураи",
    "Экшен",
    "Пародия",
    "Повседневность",
    "Меха",
    "Романтика",
    "Исторический",
    "Фэнтези",
    "Магия",
    "Гарем",
    "Спорт",
    "Хентай",
    "Школа",
    "Фантастика",
    "Сёдзё-ай",
    "Смена пола",
    "Додзинси",
    "Триллер",
    "Сёдзё",
    "Супер сила",
    "Детектив",
    "Военное",
    "Детское",
    "Машины",
    "Боевые искусства",
    "Безумие",
    "Сэйнэн",
    "Сёнен-ай",
    "Сёдзе-ай",
    "Гурман",
    "Космос",
    "Работа",
    "Ужасы",
    "Приключения",
    "Эротика",
] as const;

